/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-04-12 07:01:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.pos;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class notable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/workspace_ssm/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ssm/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/workspace_ssm/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ssm/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1711624598000L));
    _jspx_dependants.put("jar:file:/D:/workspace_ssm/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ssm/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/reset.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/goods/specify.css\" />	\r\n");
      out.write("<script>\r\n");
      out.write("function resetBasket() {\r\n");
      out.write("    // 결과를 표시할 테이블\r\n");
      out.write("    var basketTable = document.querySelector('.basket');\r\n");
      out.write("\r\n");
      out.write("    // 테이블의 모든 행 삭제\r\n");
      out.write("    while (basketTable.rows.length > 1) {\r\n");
      out.write("        basketTable.deleteRow(1); // 테이블의 첫 번째 행을 제외한 나머지 행 삭제\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("function updateGoods() {\r\n");
      out.write("	var jarr = new Array();\r\n");
      out.write("   \r\n");
      out.write("	var basketTable = document.querySelector('.basket');\r\n");
      out.write("    var rows = basketTable.getElementsByTagName('tr');\r\n");
      out.write("    \r\n");
      out.write("    // 두 번째 테이블의 각 행을 순회하며 상품 이름, 수량 및 오늘 날짜를 출력\r\n");
      out.write("    var today = new Date(); // 오늘 날짜\r\n");
      out.write("    var formattedDate = today.getFullYear() + '-' + ('0' + (today.getMonth() + 1)).slice(-2); // YYYY-MM 형식으로 변환\r\n");
      out.write("\r\n");
      out.write("    for (var i = 1; i < rows.length; i++) {\r\n");
      out.write("        var cells = rows[i].cells;\r\n");
      out.write("        var productName = cells[0].textContent; // 상품 이름\r\n");
      out.write("        var inputQuantity = cells[1].querySelector('input').value; // 수량 input 태그\r\n");
      out.write("        var salePrice = cells[2].textContent;\r\n");
      out.write("        var id= $(\"#testid\").val()\r\n");
      out.write("        console.log(\"판매가, \" + salePrice + \"상품 이름:\" + productName + \"수량:\" + inputQuantity + \"날짜:\" + formattedDate);\r\n");
      out.write("    \r\n");
      out.write("        var productInfo = {\r\n");
      out.write("        		id: id,\r\n");
      out.write("                name: productName,\r\n");
      out.write("                quantity: inputQuantity,\r\n");
      out.write("                date: formattedDate,\r\n");
      out.write("                salePrice: salePrice\r\n");
      out.write("            };\r\n");
      out.write("        jarr.push(productInfo);   \r\n");
      out.write("    }\r\n");
      out.write("    console.log(JSON.stringify(jarr));\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    $.ajax({\r\n");
      out.write("        type: \"POST\",\r\n");
      out.write("        url: \"saleinsert.do\",\r\n");
      out.write("        data: JSON.stringify(jarr),\r\n");
      out.write("        contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("        success: function(result) {\r\n");
      out.write("        	alert(\"계산 성공\")\r\n");
      out.write("            location.reload();  \r\n");
      out.write("        },\r\n");
      out.write("        error: function(request, status, errorData) {\r\n");
      out.write("            console.log(\"error code : \" + request.status\r\n");
      out.write("                + \"\\nMessage : \" + request.responseText\r\n");
      out.write("                + \"\\nError : \" + errorData);\r\n");
      out.write("        } \r\n");
      out.write("    });  \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    $.ajax({\r\n");
      out.write("        type: \"POST\",\r\n");
      out.write("        url: \"gupdatebyname.do\",\r\n");
      out.write("        data: JSON.stringify(jarr),\r\n");
      out.write("        contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("        success: function(result) {\r\n");
      out.write("            location.reload();  \r\n");
      out.write("        },\r\n");
      out.write("        error: function(request, status, errorData) {\r\n");
      out.write("            console.log(\"error code : \" + request.status\r\n");
      out.write("                + \"\\nMessage : \" + request.responseText\r\n");
      out.write("                + \"\\nError : \" + errorData);\r\n");
      out.write("        } \r\n");
      out.write("    });  \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function addBasket(rowIndex) {\r\n");
      out.write("    // 결과를 표시할 테이블\r\n");
      out.write("    var basketTable = document.querySelector('.basket');\r\n");
      out.write("\r\n");
      out.write("    // 클릭된 행 가져오기\r\n");
      out.write("    var clickedRow = document.getElementById('row_' + rowIndex);\r\n");
      out.write("\r\n");
      out.write("    // 클릭된 행의 데이터 가져오기\r\n");
      out.write("    var productName = clickedRow.cells[1].textContent; // 상품명\r\n");
      out.write("    var quantity = 1; // 초기 수량\r\n");
      out.write("    var price = clickedRow.cells[3].textContent; // 판매가격\r\n");
      out.write("\r\n");
      out.write("    // 중복 상품 체크 및 수량 증가\r\n");
      out.write("    var existingRow = null;\r\n");
      out.write("    var rows = basketTable.querySelectorAll('tr');\r\n");
      out.write("    for (var i = 0; i < rows.length; i++) {\r\n");
      out.write("        var cells = rows[i].cells;\r\n");
      out.write("        if (cells[0].textContent === productName) { // 상품명으로 중복 체크\r\n");
      out.write("            existingRow = rows[i];\r\n");
      out.write("            break;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 중복된 상품이 없으면 새로운 행 생성\r\n");
      out.write("    if (!existingRow) {\r\n");
      out.write("        // 결과를 추가할 새로운 행 생성\r\n");
      out.write("        var newRow = document.createElement('tr');\r\n");
      out.write("\r\n");
      out.write("        // 상품명 셀 생성 및 값 설정\r\n");
      out.write("        var productNameCell = document.createElement('td');\r\n");
      out.write("        productNameCell.textContent = productName;\r\n");
      out.write("        newRow.appendChild(productNameCell);\r\n");
      out.write("\r\n");
      out.write("        // 수량 셀 생성 및 값 설정\r\n");
      out.write("        var quantityCell = document.createElement('td');\r\n");
      out.write("\r\n");
      out.write("        // 수량 입력란 생성\r\n");
      out.write("        var quantityInput = document.createElement('input');\r\n");
      out.write("        quantityInput.type = 'number';\r\n");
      out.write("        quantityInput.style.width = '70px'; // 너비 설정\r\n");
      out.write("        quantityInput.style.marginRight = '0px';\r\n");
      out.write("        quantityInput.style.verticalAlign = 'middle';\r\n");
      out.write("        quantityInput.value = quantity;\r\n");
      out.write("        quantityInput.addEventListener('input', function() {\r\n");
      out.write("            // 수량이 변경될 때마다 가격 업데이트\r\n");
      out.write("            var inputPrice = parseInt(this.value) * parseInt(price);\r\n");
      out.write("            priceCell.textContent = inputPrice; // 소수점 처리 없음\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // td 셀에 input 태그 추가\r\n");
      out.write("        quantityCell.appendChild(quantityInput);\r\n");
      out.write("        newRow.appendChild(quantityCell); // 수량 셀을 새로운 행에 추가\r\n");
      out.write("\r\n");
      out.write("        // 판매가격 셀 생성 및 값 설정\r\n");
      out.write("        var priceCell = document.createElement('td');\r\n");
      out.write("        var inputPrice = parseInt(quantity) * parseInt(price);\r\n");
      out.write("        priceCell.textContent = inputPrice; // 소수점 처리 없음\r\n");
      out.write("        newRow.appendChild(priceCell);\r\n");
      out.write("\r\n");
      out.write("        // 결과 테이블에 새로운 행 추가\r\n");
      out.write("        basketTable.appendChild(newRow);\r\n");
      out.write("    } else { // 중복된 상품이 있으면 수량 증가\r\n");
      out.write("        var inputElement = existingRow.querySelector('input');\r\n");
      out.write("        inputElement.value = parseInt(inputElement.value) + 1;\r\n");
      out.write("        inputElement.dispatchEvent(new Event('input')); // 수량이 변경되었음을 알림\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write(".wrap {\r\n");
      out.write("	width: 1000px;\r\n");
      out.write("	padding: 10px 600px 50px 600px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("	background-color: orange;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 10vh;	\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: nowrap;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".body, .footer {\r\n");
      out.write("	background-color: lightgray;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".body {\r\n");
      out.write("	height: 60vh;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.goods {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.bascket {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	right: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".body .tableView {\r\n");
      out.write("	width: 80%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	padding: 30px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".buttonList{\r\n");
      out.write("	background-color: lightgray;\r\n");
      out.write("	text-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".title p {\r\n");
      out.write("	color: black;\r\n");
      out.write("	font-weight: bolder;\r\n");
      out.write("	padding-right: 20px; \r\n");
      out.write("}\r\n");
      out.write(".header a{\r\n");
      out.write("	color:black;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	left: 10px;\r\n");
      out.write("	top: 50%;\r\n");
      out.write("	transform: translateY(-50%);\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("	padding: 15px 32px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	margin: 4px 2px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	font-weight: 800;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	weight: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 테이블 추가 버튼 */\r\n");
      out.write(".button.add {\r\n");
      out.write("	background-color: DodgerBlue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 테이블 삭제 버튼 */\r\n");
      out.write(".button.delete {\r\n");
      out.write("	background-color: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"/ssm/resources/js/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/ssm/resources/css/jquery-ui-1.13.2/jquery-ui.min.css\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"/ssm/resources/css/jquery-ui-1.13.2/jquery-ui.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<title>SSM웹포스기 세팅화면</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"/ssm/resources/js/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"wrap\">\r\n");
      out.write("		<div class=\"header\">\r\n");
      out.write("			<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/glist.do?page=1&id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">재고 페이지</a>	\r\n");
      out.write("			<p class=\"title\">SSM 웹 포스기</p>					\r\n");
      out.write("		</div>\r\n");
      out.write("		 \r\n");
      out.write("		<div class=\"body\">\r\n");
      out.write("			<div class=\"table1\" style=\"margin-left: auto; margin-right: auto; width: 500px;\">\r\n");
      out.write("				<input type=\"hidden\" id=\"id\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUser.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">			\r\n");
      out.write("				<table class=\"goods\" align=\"center\" border=\"1\" cellspacing=\"25\"\r\n");
      out.write("					width=\"60%\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th style=\"text-align: center; white-space: nowrap;\">번호</th>\r\n");
      out.write("						<th style=\"text-align: center; white-space: nowrap;\">상품명</th>\r\n");
      out.write("						<th style=\"text-align: center; white-space: nowrap;\">남은 수량</th>\r\n");
      out.write("						<th style=\"text-align: center; white-space: nowrap;\">판매가격</th>\r\n");
      out.write("					</tr>					\r\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				</table>				\r\n");
      out.write("			</div>	<!-- div 표1 -->	\r\n");
      out.write("			<div class=\"table2\" >			\r\n");
      out.write("				<table class=\"basket\"  border=\"1\" cellspacing=\"25\"width=\"30%\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th style=\"text-align: center; white-space: nowrap;\">상품명</th>\r\n");
      out.write("						<th style=\"text-align: center; white-space: nowrap;\">수량</th>\r\n");
      out.write("						<th style=\"text-align: center; white-space: nowrap;\">판매가격</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div> <!-- div 표2 -->			\r\n");
      out.write("		</div> <!-- div class=\"body\" -->\r\n");
      out.write("		<div class=\"buttonList\">\r\n");
      out.write("			<button align=\"right\" class=\"button add\" onclick=\"updateGoods()\">계산</button>\r\n");
      out.write("			<button align=\"right\" class=\"button delete\" onclick=\"resetBasket()\">취소</button>\r\n");
      out.write("			<input type=\"hidden\" id=\"userId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		</div>	\r\n");
      out.write("	</div> <!-- 전체 -->\r\n");
      out.write("	\r\n");
      out.write("	<input type=\"hidden\" id =\"testid\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUser.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/pos/notable.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("nowpage");
      // /WEB-INF/views/pos/notable.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/pos/notable.jsp(7,0) '1'",_jsp_getExpressionFactory().createValueExpression("1",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/pos/notable.jsp(8,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty requestScope.currentPage }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\r');
          out.write('\n');
          out.write('	');
          if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/pos/notable.jsp(9,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("nowpage");
      // /WEB-INF/views/pos/notable.jsp(9,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/pos/notable.jsp(9,1) '${requestScope.currentPage }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${requestScope.currentPage }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/pos/notable.jsp(300,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/pos/notable.jsp(300,5) '${requestScope.list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${requestScope.list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/pos/notable.jsp(300,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("goodsPrint");
      // /WEB-INF/views/pos/notable.jsp(300,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("loop");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("						<tr id=\"row_");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("							<td align=\"center\" style=\"white-space: nowrap;\"\r\n");
            out.write("								onclick=\"addBasket(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(')');
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsPrint.goodsNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("							<td align=\"center\" style=\"white-space: nowrap;\"\r\n");
            out.write("								onclick=\"addBasket(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(')');
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsPrint.goodsName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("							<td align=\"center\" style=\"white-space: nowrap;\"\r\n");
            out.write("								onclick=\"addBasket(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(')');
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsPrint.pdQuantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("							<td align=\"center\" style=\"white-space: nowrap;\"\r\n");
            out.write("								onclick=\"addBasket(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(')');
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsPrint.salePrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						</tr>					\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
