/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-04-10 06:40:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.subscribe;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class subscribeListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/workspace_ssm/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ssm/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/workspace_ssm/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ssm/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1711624598000L));
    _jspx_dependants.put("jar:file:/D:/workspace_ssm/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ssm/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>구독상품페이지</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	font-family: arial;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	margin: 25px auto;\r\n");
      out.write("	width: 1200px;\r\n");
      out.write("	outline: dashed 1px black;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	width: 900px;\r\n");
      out.write("	margin: 1rem auto;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("thead {\r\n");
      out.write("	box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 테이블 행 */\r\n");
      out.write("td {\r\n");
      out.write("	padding: 8px;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	border-bottom: 1px solid #ddd;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("	padding: 8px;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	border-top: 2px solid #000;\r\n");
      out.write("	border-bottom: 2px solid #000;\r\n");
      out.write("	color: #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 테이블 올렸을 때 */\r\n");
      out.write("tbody tr:not(#titlerow):hover {\r\n");
      out.write("	background-color: rgb(255, 221, 102);\r\n");
      out.write("	opacity: 0.9;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 테이블 비율 */\r\n");
      out.write("th:nth-child(1) {\r\n");
      out.write("	width: 10%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th:nth-child(2) {\r\n");
      out.write("	width: 10%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th:nth-child(3) {\r\n");
      out.write("	width: 30%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th:nth-child(4) {\r\n");
      out.write("	width: 30%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th:nth-child(5) {\r\n");
      out.write("	width: 20%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th, td {\r\n");
      out.write("	border-left: none;\r\n");
      out.write("	border-right: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button#payment-button {\r\n");
      out.write("	width: 200px;\r\n");
      out.write("	height: 80px;\r\n");
      out.write("	border: orange;\r\n");
      out.write("	background: rgb(250, 180, 49);\r\n");
      out.write("	color: #ffffff;\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("	margin-top: 50px;\r\n");
      out.write("	margin-bottom: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p.title {\r\n");
      out.write("	margin: 0 0 70px;\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	color: #4e5968;\r\n");
      out.write("}\r\n");
      out.write("/*결제 로고*/\r\n");
      out.write("#payment-method img {\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write("/* 이미지에 마우스를 올렸을 때 */\r\n");
      out.write("#payment-method img:hover {\r\n");
      out.write("	transform: scale(1.05); /* 이미지 크기를 약간 키움 */\r\n");
      out.write("	transition: transform 0.3s ease; /* 부드럽게 변화되도록 애니메이션 적용 */\r\n");
      out.write("	cursor: pointer; /* 커서 모양을 손가락으로 변경 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 이미지를 선택했을 때 */\r\n");
      out.write("img.selected {\r\n");
      out.write("	border: 2px solid blue; /* 이미지 주변에 파란색 테두리 추가 */\r\n");
      out.write("}\r\n");
      out.write("/*결제 div*/\r\n");
      out.write("#payment-method {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-around; /* 가로로 배치하고 가운데 정렬 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".payment-section {\r\n");
      out.write("	width: 30%; /* 각 구역의 너비 */\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	border: 1px solid #ccc; /* 테두리 설정 */\r\n");
      out.write("	background-color: #f9f9f9; /* 배경색 설정 */\r\n");
      out.write("	text-align: center; /* 텍스트 가운데 정렬 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".payment-section p {\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*약관*/\r\n");
      out.write(".payment-option {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	background-color: #f9f9f9;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".payment-option label {\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".payment-option input[type=\"checkbox\"] {\r\n");
      out.write("	margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#option-1-checkbox, #option-2-checkbox, #option-3-checkbox {\r\n");
      out.write("	float: left;\r\n");
      out.write("	margin-right: 5px;\r\n");
      out.write("	width: 20px;\r\n");
      out.write("	height: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".payment-option a {\r\n");
      out.write("	float: right;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".agree {\r\n");
      out.write("	width: 500px;\r\n");
      out.write("	height: 100px;\r\n");
      out.write("	border: 1px solid black;\r\n");
      out.write("	overflow-y: scroll;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".agreeDetail {\r\n");
      out.write("	font-size: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"/ssm/resources/js/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"https://cdn.iamport.kr/js/iamport.payment-1.1.5.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"/ssm/resources/js/subscribe/subscribe.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<div class=\"main-container\" style=\"padding-top:100px;\">\r\n");
      out.write("	<hr>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("	<input id=\"message\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.message }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		<div class=\"subscribeList\">\r\n");
      out.write("			<p class=\"title\">구독 상품</p>\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr id=\"titlerow\">\r\n");
      out.write("					<th></th>\r\n");
      out.write("					<th>상품번호</th>\r\n");
      out.write("					<th>상품이름</th>\r\n");
      out.write("					<th>가격</th>\r\n");
      out.write("					<th>기간</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<br>\r\n");
      out.write("		<p class=\"title\">결제 방법</p>\r\n");
      out.write("		<div id=\"payment-method\">\r\n");
      out.write("			<div class=\"payment-section\" id=\"mobile-payment\">\r\n");
      out.write("				<p class=\"title\">모바일 결제</p>\r\n");
      out.write("				<img src=\"resources/images/paylogo/danal.png\"\r\n");
      out.write("					data-payment-method=\"danal\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"payment-section\" id=\"easy-payment\">\r\n");
      out.write("				<p class=\"title\">간편 결제</p>\r\n");
      out.write("				<img src=\"resources/images/paylogo/kakao.jpg\"\r\n");
      out.write("					data-payment-method=\"kakaopay\"><img\r\n");
      out.write("					src=\"resources/images/paylogo/toss.jpg\"\r\n");
      out.write("					data-payment-method=\"tosspay\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"payment-section\" id=\"card-payment\">\r\n");
      out.write("				<p class=\"title\">카드 결제</p>\r\n");
      out.write("				<img src=\"resources/images/paylogo/danal.png\"\r\n");
      out.write("					data-payment-method=\"danal_tpay\"> <img\r\n");
      out.write("					src=\"resources/images/paylogo/kginicis.jpg\"\r\n");
      out.write("					data-payment-method=\"html5_inicis\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<br>\r\n");
      out.write("		\r\n");
      out.write("			<p class=\"title\">이용약관</p>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"agreement\"\r\n");
      out.write("			style=\"width: 700px; margin: 0 auto; text-align: center;\">\r\n");
      out.write("			<div class=\"payment-option\" id=\"payment-option-1\"\r\n");
      out.write("				style=\"margin-bottom: 20px;\">\r\n");
      out.write("				<input type=\"checkbox\" id=\"option-1-checkbox\"> <label\r\n");
      out.write("					for=\"option-1-checkbox\">회원 탈퇴 및 자격 상실 등</label> <a\r\n");
      out.write("					onclick=\"showDetail(1);\">자세히</a>\r\n");
      out.write("				<p class=\"agreeDetail\" id=\"detail-1\" style=\"display: none;\">①\r\n");
      out.write("					회원은 “SSSM”에 언제든지 탈퇴를 요청할 수 있으며 “SSSM”은 즉시 회원탈퇴를 처리합니다. ② 회원이 다음 각 호의 사유에\r\n");
      out.write("					해당하는 경우, “SSSM”은 회원자격을 제한 및 정지시킬 수 있습니다. 1. 가입 신청 시에 허위 내용을 등록한 경우 2.\r\n");
      out.write("					“SSSM”을 이용하여 구입한 재화 등의 대금, 기타 “SSSM”이용에 관련하여 회원이 부담하는 채무를 기일에 지급하지 않는 경우\r\n");
      out.write("\r\n");
      out.write("					3. 다른 사람의 “SSSM” 이용을 방해하거나 그 정보를 도용하는 등 전자상거래 질서를 위협하는 경우 4. “SSSM”을 이용하여\r\n");
      out.write("					법령 또는 이 약관이 금지하거나 공서양속에 반하는 행위를 하는 경우 ③ “SSSM”이 회원 자격을 제한․정지 시킨 후, 동일한\r\n");
      out.write("					행위가 2회 이상 반복되거나 30일 이내에 그 사유가 시정되지 아니하는 경우 “SSSM”은 회원자격을 상실시킬 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					④ “SSSM”이 회원자격을 상실시키는 경우에는 회원등록을 말소합니다. 이 경우 회원에게 이를 통지하고, 회원등록 말소 전에\r\n");
      out.write("					최소한 30일 이상의 기간을 정하여 소명할 기회를 부여합니다.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"payment-option\" id=\"payment-option-2\"\r\n");
      out.write("				style=\"margin-bottom: 20px;\">\r\n");
      out.write("				<input type=\"checkbox\" id=\"option-2-checkbox\"> <label\r\n");
      out.write("					for=\"option-2-checkbox\">청약철회</label> <a onclick=\"showDetail(2);\">자세히</a>\r\n");
      out.write("				<p class=\"agreeDetail\" id=\"detail-2\" style=\"display: none;\">①\r\n");
      out.write("					“SSSM”이용자는 SSSM몰”상에서 다음 또는 이와 유사한 방법에 의하여 구매를 신청하며, “몰”은 이용자가 구매신청을 함에\r\n");
      out.write("					있어서 다음의 각 내용을 알기 쉽게 제공하여야 합니다. 1. 재화 등의 검색 및 선택 2. 받는 사람의 성명, 주소,\r\n");
      out.write("					전화번호, 전자우편주소(또는 이동전화번호) 등의 입력 3. 약관내용, 청약철회권이 제한되는 서비스, 배송료․설치비 등의\r\n");
      out.write("					비용부담과 관련한 내용에 대한 확인 4. 이 약관에 동의하고 위 3.호의 사항을 확인하거나 거부하는 표시 (예, 마우스\r\n");
      out.write("					클릭) 5. 재화등의 구매신청 및 이에 관한 확인 또는 “몰”의 확인에 대한 동의 6. 결제방법의 선택 ② “몰”이\r\n");
      out.write("					제3자에게 구매자 개인정보를 제공할 필요가 있는 경우 1) 개인정보를 제공받는 자, 2)개인정보를 제공받는 자의 개인정보\r\n");
      out.write("					이용목적, 3) 제공하는 개인정보의 항목, 4) 개인정보를 제공받는 자의 개인정보 보유 및 이용기간을 구매자에게 알리고\r\n");
      out.write("					동의를 받아야 합니다. (동의를 받은 사항이 변경되는 경우에도 같습니다.) ③ “SSSM”이 제3자에게 구매자의 개인정보를\r\n");
      out.write("					취급할 수 있도록 업무를 위탁하는 경우에는 1) 개인정보 취급위탁을 받는 자, 2) 개인정보 취급위탁을 하는 업무의\r\n");
      out.write("					내용을 구매자에게 알리고 동의를 받아야 합니다. (동의를 받은 사항이 변경되는 경우에도 같습니다.) 다만, 서비스제공에\r\n");
      out.write("					관한 계약이행을 위해 필요하고 구매자의 편의증진과 관련된 경우에는 「정보통신망 이용촉진 및 정보보호 등에 관한 법률」에서\r\n");
      out.write("					정하고 있는 방법으로 개인정보 취급방침을 통해 알림으로써 고지절차와 동의절차를 거치지 않아도 됩니다.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"payment-option\" id=\"payment-option-3\">\r\n");
      out.write("				<input type=\"checkbox\" id=\"option-3-checkbox\"> <label\r\n");
      out.write("					for=\"option-3-checkbox\">결제 취소 및 환불</label> <a\r\n");
      out.write("					onclick=\"showDetail(3);\">자세히</a>\r\n");
      out.write("				<p class=\"agreeDetail\" id=\"detail-3\" style=\"display: none;\">①\r\n");
      out.write("					“SSSM”과 재화등의 구매에 관한 계약을 체결한 이용자는 「전자상거래 등에서의 소비자보호에 관한 법률」 제13조 제2항에\r\n");
      out.write("					따른 계약내용에 관한 서면을 받은 날(그 서면을 받은 때보다 재화 등의 공급이 늦게 이루어진 경우에는 재화 등을\r\n");
      out.write("					공급받거나 재화 등의 공급이 시작된 날을 말합니다)부터 7일 이내에는 청약의 철회를 할 수 있습니다. 다만, 청약철회에\r\n");
      out.write("					관하여 「전자상거래 등에서의 소비자보호에 관한 법률」에 달리 정함이 있는 경우에는 동 법 규정에 따릅니다. ② 이용자는\r\n");
      out.write("					재화 등을 배송 받은 경우 다음 각 호의 1에 해당하는 경우에는 반품 및 교환을 할 수 없습니다. 1. 이용자에게 책임\r\n");
      out.write("					있는 사유로 재화 등이 멸실 또는 훼손된 경우(다만, 재화 등의 내용을 확인하기 위하여 포장 등을 훼손한 경우에는\r\n");
      out.write("					청약철회를 할 수 있습니다) 2. 이용자의 사용 또는 일부 소비에 의하여 재화 등의 가치가 현저히 감소한 경우 3.\r\n");
      out.write("					시간의 경과에 의하여 재판매가 곤란할 정도로 재화등의 가치가 현저히 감소한 경우 4. 같은 성능을 지닌 재화 등으로\r\n");
      out.write("					복제가 가능한 경우 그 원본인 재화 등의 포장을 훼손한 경우 ③ 제2항제2호 내지 제4호의 경우에 “몰”이 사전에\r\n");
      out.write("					청약철회 등이 제한되는 사실을 소비자가 쉽게 알 수 있는 곳에 명기하거나 시용상품을 제공하는 등의 조치를 하지 않았다면\r\n");
      out.write("					이용자의 청약철회 등이 제한되지 않습니다. ④ 이용자는 제1항 및 제2항의 규정에 불구하고 재화 등의 내용이 표시·광고\r\n");
      out.write("					내용과 다르거나 계약내용과 다르게 이행된 때에는 당해 재화 등을 공급받은 날부터 3월 이내, 그 사실을 안 날 또는 알\r\n");
      out.write("					수 있었던 날부터 30일 이내에 청약철회 등을 할 수 있습니다.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<input id=\"email\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <input\r\n");
      out.write("			id=\"businessStoreName\" type=\"hidden\"\r\n");
      out.write("			value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.businessStoreName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <input id=\"phone\"\r\n");
      out.write("			type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <input id=\"userId\"\r\n");
      out.write("			type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <input id=\"id\"\r\n");
      out.write("			type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		<!-- 로그인유저 아이디랑 , 상품번호도 보내야함! -->\r\n");
      out.write("		<br> <br> <br> <br> <br>\r\n");
      out.write("		<button id=\"payment-button\" onclick=\"pay();\">결제하기</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<hr>\r\n");
      out.write("	");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/subscribe/subscribeListView.jsp(189,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/WEB-INF/views/common/header.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/subscribe/subscribeListView.jsp(206,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/subscribe/subscribeListView.jsp(206,4) '${ requestScope.list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ requestScope.list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/subscribe/subscribeListView.jsp(206,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("s");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					<tr>\r\n");
            out.write("						<td><input type=\"checkbox\"></td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.subscribeNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.subscribeName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.subscribeDate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("개월</td>\r\n");
            out.write("					</tr>\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/views/subscribe/subscribeListView.jsp(320,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("/WEB-INF/views/common/footer.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
